language: objective-c
before_install:
    - brew update
    - brew uninstall xctool && brew install xctool --HEAD
script: xctool -workspace Anthropocene.xcworkspace -scheme 'Anthropocene Example' -sdk macosx -configuration Release
